import { test, expect, createProject, configureModel, createAndBindAgent } from './fixtures'

test('Channel members, custom configuration, recommended imports and existing Agents persist independently', async ({ desktop, provider }) => {
  const { page } = desktop
  await page.setViewportSize({ width: 1440, height: 900 })
  await createProject(desktop)
  await configureModel(page, provider.url)
  const manager = page.getByRole('region', { name: 'Agent 管理', exact: true })
  await expect(manager.getByText('当前群聊还没有 Agent', { exact: true })).toBeVisible()
  await expect(manager.getByLabel('Agent 名称', { exact: true })).toHaveCount(0)
  await createAndBindAgent(page, [], '选题策划师', '💡')
  await expect(manager.getByText('选题策划师', { exact: true })).toBeVisible()
  await expect(manager.getByLabel('发言模式', { exact: true })).toBeHidden()

  await manager.getByRole('button', { name: '＋ 添加 Agent', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: '添加 Agent', exact: true })
  await dialog.getByRole('button', { name: '推荐实例', exact: true }).click()
  await expect(dialog.getByRole('button', { name: '导入 Agent：内容主编 (PM)', exact: true })).toBeEnabled()
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/agent-add-recommended.png' })
  await dialog.getByRole('button', { name: '导入 Agent：内容主编 (PM)', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(manager.getByText('内容主编 (PM)', { exact: true })).toBeVisible()

  await manager.getByRole('button', { name: '编辑 Agent：选题策划师', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '编辑 Agent', exact: true })
  await editor.getByLabel('Agent 角色', { exact: true }).fill('围绕读者需求规划选题')
  await page.screenshot({ path: 'test-results/agent-custom-editor.png' })
  await editor.getByRole('button', { name: '保存 Agent', exact: true }).click()
  await expect(editor).toHaveCount(0)
  await expect(manager.getByText('围绕读者需求规划选题', { exact: true })).toBeVisible()
  await manager.getByRole('button', { name: '停用群聊 Agent：选题策划师', exact: true }).click()
  await expect(manager.getByRole('button', { name: '启用群聊 Agent：选题策划师', exact: true })).toBeEnabled()
  await page.screenshot({ path: 'test-results/agent-current-members.png' })

  await page.getByRole('button', { name: '新建会话群聊', exact: true }).click()
  await page.getByLabel('群聊名称', { exact: true }).fill('独立选题讨论')
  await page.getByRole('button', { name: '确认建群', exact: true }).click()
  await expect(manager.getByText('当前群聊还没有 Agent', { exact: true })).toBeVisible()
  await expect(manager.getByText('选题策划师', { exact: true })).toHaveCount(0)
  await manager.getByRole('button', { name: '＋ 添加 Agent', exact: true }).click()
  dialog = page.getByRole('dialog', { name: '添加 Agent', exact: true })
  await dialog.getByRole('button', { name: '已有 Agent', exact: true }).click()
  await dialog.getByRole('button', { name: '加入群聊：选题策划师', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(manager.getByRole('button', { name: '停用群聊 Agent：选题策划师', exact: true })).toBeEnabled()
  await expect(manager.getByText('内容主编 (PM)', { exact: true })).toHaveCount(0)
  await manager.getByRole('button', { name: '移出群聊：选题策划师', exact: true }).click()
  await expect(manager.getByText('当前群聊还没有 Agent', { exact: true })).toBeVisible()

  const [project] = await page.evaluate(() => window.agentTeam.projects.list())
  const channels = await page.evaluate((id) => window.agentTeam.channels.list(id), project.id)
  const main = channels.find((channel) => channel.name === '主线任务协同群')!
  const other = channels.find((channel) => channel.name === '独立选题讨论')!
  const originalMembers = await page.evaluate((id) => window.agentTeam.channelAgents.list(id), main.id)
  expect(originalMembers).toHaveLength(2)
  expect(originalMembers.filter((member) => member.isEnabled)).toHaveLength(1)
  await desktop.restart()
  expect(await desktop.page.evaluate((id) => window.agentTeam.channelAgents.list(id), main.id)).toEqual(originalMembers)
  expect(await desktop.page.evaluate((id) => window.agentTeam.channelAgents.list(id), other.id)).toHaveLength(0)
  expect(await desktop.page.evaluate(() => window.agentTeam.agents.list())).toHaveLength(2)
  expect(provider.requests).toHaveLength(0)
})
