import { test, expect, createProject, configureModel, createAndBindAgent } from './fixtures'

test('actual Agent requests include the current group roster and Markdown renders during streaming and after restart', async ({ desktop, provider }) => {
  const { page } = desktop
  await page.setViewportSize({ width: 1440, height: 1050 })
  await createProject(desktop)
  await configureModel(page, provider.url)
  await createAndBindAgent(page, [], '内容主编', '📰')
  await createAndBindAgent(page, [], '写作者', '✍️')
  await createAndBindAgent(page, [], '审核员', '🔎')
  await page.getByRole('button', { name: '停用群聊 Agent：审核员', exact: true }).click()
  await expect(page.getByRole('button', { name: '启用群聊 Agent：审核员', exact: true })).toBeEnabled()
  const [project] = await page.evaluate(() => window.agentTeam.projects.list())
  const [main] = await page.evaluate((id) => window.agentTeam.channels.list(id), project.id)
  await page.getByRole('button', { name: '新建会话群聊', exact: true }).click()
  await page.getByLabel('群聊名称', { exact: true }).fill('其他群聊')
  await page.getByRole('button', { name: '确认建群', exact: true }).click()
  await expect(page.getByRole('heading', { name: '其他群聊', exact: true })).toBeVisible()
  await createAndBindAgent(page, [], '其他群聊独有成员', '🚧')
  await page.getByRole('button', { name: '主线任务协同群', exact: true }).click()
  await expect(page.getByRole('button', { name: '停用群聊 Agent：内容主编', exact: true })).toBeEnabled()
  await page.getByLabel('消息内容', { exact: true }).fill('根据当前群聊成员名单给出协作建议，用 Markdown 展示。 ')
  await page.getByLabel('@ 指派成员', { exact: true }).selectOption({ label: '内容主编' })
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const consent = page.getByRole('dialog', { name: '云端模型授权', exact: true })
  await expect(consent).toContainText('当前群聊 Agent 成员名单与启用状态')
  await consent.getByRole('checkbox').check()
  await consent.getByRole('button', { name: '同意并发送', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(1)
  const system = provider.requests[0].messages[0].content!
  const facts = JSON.parse(system.split('Authoritative task facts (only these records establish state):\n')[1].split('\n')[0])
  expect(facts.channelMembers).toMatchObject({ channelId: main.id, total: 3, enabledCount: 2 })
  expect(facts.channelMembers.members.map((member: { name: string; isEnabled: boolean }) => [member.name, member.isEnabled])).toEqual([['内容主编', true], ['写作者', true], ['审核员', false]])
  expect(system).not.toContain('其他群聊独有成员')
  const prefix = '# 当前群聊成员\n\n**共有 3 位 Agent**，其中 2 位已启用。\n\n'
  const body = '| 成员 | 状态 |\n| --- | --- |\n| 内容主编 | 已启用 |\n| 写作者 | 已启用 |\n| 审核员 | 已停用 |\n\n- 内容主编负责统筹\n- 写作者负责写作\n\n> 主理人单独计算，启用状态不代表在线。\n\n```js\nconst enabledAgents = 2\n```'
  provider.delta(prefix)
  const log = page.getByRole('log', { name: '群聊消息', exact: true })
  await expect(log.getByRole('heading', { name: '当前群聊成员', level: 1 })).toBeVisible()
  await expect(log.locator('strong').filter({ hasText: '共有 3 位 Agent' })).toBeVisible()
  provider.delta(body); provider.complete()
  await expect(log.getByRole('table')).toContainText('审核员')
  await expect(log.locator('pre code')).toHaveText('const enabledAgents = 2\n')
  await expect(page.getByRole('region', { name: 'CEO 任务控制' })).toHaveCount(0)
  const messages = await page.evaluate((id) => window.agentTeam.messages.list(id), main.id)
  expect(messages.find((message) => message.origin === 'agent')?.content).toBe(prefix + body)
  await page.screenshot({ path: 'test-results/message-markdown-members-light.png' })
  await page.getByRole('combobox', { name: '界面主题', exact: true }).selectOption('dark')
  await page.screenshot({ path: 'test-results/message-markdown-members-dark.png' })
  await desktop.restart()
  await expect(desktop.page.getByRole('log').getByRole('heading', { name: '当前群聊成员', level: 1 })).toBeVisible()
  await expect(desktop.page.getByRole('log').getByRole('table')).toContainText('审核员')
  expect(provider.requests).toHaveLength(1)

  // The next model request must reflect member removal, not a cached earlier roster.
  await desktop.page.getByRole('button', { name: '移出群聊：审核员', exact: true }).click()
  await expect(desktop.page.getByRole('button', { name: '移出群聊：审核员', exact: true })).toHaveCount(0)
  await desktop.page.getByLabel('消息内容', { exact: true }).fill('根据更新后的群聊成员名单给出协作建议。 ')
  await desktop.page.getByLabel('@ 指派成员', { exact: true }).selectOption({ label: '内容主编' })
  await desktop.page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(2)
  const latestSystem = provider.requests[1].messages[0].content!
  const latestFacts = JSON.parse(latestSystem.split('Authoritative task facts (only these records establish state):\n')[1].split('\n')[0])
  expect(latestFacts.channelMembers).toMatchObject({ total: 2, enabledCount: 2 })
  expect(latestFacts.channelMembers.members.map((member: { name: string }) => member.name)).toEqual(['内容主编', '写作者'])
  provider.delta('当前群聊有 **2 位 Agent**。'); provider.complete()
  await expect(desktop.page.getByRole('log').locator('strong').filter({ hasText: '2 位 Agent' })).toBeVisible()
})
