import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { Page } from 'playwright/test'
import { test, expect, configureModel, createAndBindAgent, createProject, sendWithConsent, writeWorkspaceFile, type Desktop, type Provider } from './fixtures'

async function snapshot(page: Page) {
  return page.evaluate(async () => {
    const [project] = await window.agentTeam.projects.list()
    const [channel] = await window.agentTeam.channels.list(project.id)
    return window.agentTeam.tasks.snapshot(channel.id)
  })
}

async function team(desktop: Desktop, provider: Provider, permissions: string[] = []) {
  await createProject(desktop)
  await configureModel(desktop.page, provider.url)
  await createAndBindAgent(desktop.page, permissions, 'Alpha', '🛠️')
  await createAndBindAgent(desktop.page, [], 'Beta', '📝')
  return (await snapshot(desktop.page)).agents
}

async function mentions(page: Page, names: string[], content = '请按顺序协作 ') {
  await page.getByLabel('消息内容', { exact: true }).fill(content)
  for (const name of names) {
    await page.getByLabel('消息内容', { exact: true }).press('End')
    await page.getByLabel('@ 指派成员', { exact: true }).selectOption({ label: name })
  }
  await expect(page.getByRole('list', { name: '指派顺序' }).getByRole('listitem')).toHaveText(names.map((name, i) => `${i + 1}. @${name}`))
}

async function submitFirst(page: Page) {
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const consent = page.getByRole('dialog', { name: '云端模型授权' })
  await expect(consent).toBeVisible()
  await expect(consent).toContainText('Agent Alpha')
  await expect(consent.getByRole('button', { name: '同意并发送', exact: true })).toBeDisabled()
  await consent.getByRole('checkbox').check()
  await consent.getByRole('button', { name: '同意并发送', exact: true }).click()
}

async function paused(page: Page) {
  await expect(page.getByRole('button', { name: '继续当前任务', exact: true })).toBeEnabled()
  await expect.poll(async () => (await snapshot(page)).runs.at(-1)?.status).toBe('paused')
}

test('CEO structured Alpha/Beta mentions run in order with durable identities and reload without duplicates', async ({ desktop, provider }) => {
  const agents = await team(desktop, provider)
  const { page } = desktop
  await mentions(page, ['Alpha', 'Beta'])
  await submitFirst(page)
  await expect.poll(() => provider.requests.length).toBe(1)
  expect(JSON.stringify(provider.requests[0].messages)).toContain('你是 Alpha')
  provider.delta('Alpha 已完成第一项分析。')
  await expect(page.getByRole('log')).toContainText('Alpha 已完成第一项分析。')
  await expect(page.getByRole('region', { name: 'CEO 任务控制' })).toContainText('当前发言：Alpha')
  provider.complete()
  await expect.poll(() => provider.requests.length).toBe(2)
  expect(JSON.stringify(provider.requests[1].messages)).toContain('你是 Beta')
  provider.delta('Beta 已核对并补充交付结论。'); provider.complete()
  await paused(page)
  const durable = await snapshot(page)
  expect(durable.turns.map((turn) => [turn.agentId, turn.status])).toEqual(agents.map((agent) => [agent.id, 'completed']))
  expect(durable.messages.map((message) => message.authorName)).toEqual(['CEO', 'Alpha', 'Beta'])
  expect(new Set(durable.events.map((event) => event.seq)).size).toBe(durable.events.length)
  expect(durable.events.map((event) => event.seq)).toEqual([...durable.events.map((event) => event.seq)].sort((a, b) => a - b))
  expect(JSON.stringify(durable)).not.toContain('e2e-local-only-key')
  expect(JSON.stringify(durable)).not.toContain('你是 Alpha')
  expect(JSON.stringify(durable)).not.toContain(desktop.workspace)
  expect(durable.events.every((event) => !('metadataJson' in event))).toBe(true)
  await page.reload()
  await expect(page.getByRole('log').getByRole('article')).toHaveCount(3)
  await expect(page.getByRole('log').getByRole('article').nth(1)).toHaveAttribute('data-agent-id', agents[0].id)
  await expect(page.getByRole('log')).toContainText('🛠️')
  await expect(page.getByRole('log')).toContainText('📝')
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/v03-collaboration.png', fullPage: true })
  expect(provider.requests).toHaveLength(2)
})

test('a handoff only starts Beta after Alpha completed, not from a partial delta', async ({ desktop, provider }) => {
  const agents = await team(desktop, provider)
  await mentions(desktop.page, ['Alpha'])
  await submitFirst(desktop.page)
  await expect.poll(() => provider.requests.length).toBe(1)
  provider.delta('请由 @Beta 接手核对。')
  await expect(desktop.page.getByRole('log')).toContainText('请由 @Beta 接手核对。')
  expect(provider.requests).toHaveLength(1)
  expect((await snapshot(desktop.page)).turns).toHaveLength(1)
  provider.complete()
  await expect.poll(() => provider.requests.length).toBe(2)
  provider.delta('Beta 核对结束。'); provider.complete()
  await paused(desktop.page)
  expect((await snapshot(desktop.page)).turns.map((turn) => turn.agentId)).toEqual(agents.map((agent) => agent.id))
})

test('automatic scheduling uses exact schema decisions and null finishes without fabricating another speaker', async ({ desktop, provider }) => {
  const agents = await team(desktop, provider)
  const { page } = desktop
  await page.getByRole('button', { name: '模型设置', exact: true }).click()
  await page.getByRole('combobox', { name: '默认调度模型', exact: true }).selectOption({ label: 'local-e2e-model' })
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  const goal = '自动选择合适成员并完成任务 ' + 'required goal detail '.repeat(160) + '保留最终验收要求'
  await page.getByLabel('消息内容', { exact: true }).fill(goal)
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const consent = page.getByRole('dialog', { name: '云端模型授权' })
  await expect(consent).toContainText('自动选人')
  await expect(consent).toContainText('完整当前 CEO 目标')
  await expect(consent).toContainText('每 10 个完成轮次的摘要')
  expect(provider.requests).toHaveLength(0)
  await consent.getByRole('checkbox').check(); await consent.getByRole('button', { name: '同意并发送', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(1)
  expect(provider.requests[0].stream).toBe(false)
  expect(JSON.parse(provider.requests[0].messages[1].content!)).toMatchObject({ currentCeoGoal: goal, latestCompletedAgentMessage: '' })
  const [model] = await page.evaluate(() => window.agentTeam.models.list())
  const withinBudget = (index: number) => expect(Buffer.byteLength(JSON.stringify(provider.requests[index].messages), 'utf8') + 256 + provider.requests[index].max_tokens).toBeLessThanOrEqual(model.contextWindow ?? 8192)
  expect(provider.requests[0].max_tokens).toBe(model.maxOutputTokens ?? 1024)
  withinBudget(0)
  provider.json(JSON.stringify({ nextSpeaker: agents[1].id, reason: 'Beta 负责最终核对' }))
  await expect.poll(() => provider.requests.length).toBe(2)
  await expect(page.getByRole('region', { name: 'CEO 任务控制' })).toContainText('Beta 负责最终核对')
  expect(provider.requests[1].stream).toBe(true)
  provider.delta('自动选择 Beta 的交付。'); provider.complete()
  await expect.poll(() => provider.requests.length).toBe(3)
  expect(JSON.parse(provider.requests[2].messages[1].content!)).toMatchObject({ currentCeoGoal: goal, latestCompletedAgentMessage: '自动选择 Beta 的交付。' })
  withinBudget(2)
  provider.json(JSON.stringify({ nextSpeaker: null, reason: '任务已完成，无需继续发言' }))
  await expect(page.getByText('已完成', { exact: true })).toBeVisible()
  await page.reload()
  const state = await snapshot(page)
  expect(state.turns.map((turn) => turn.agentId)).toEqual([agents[1].id])
  expect(state.events.filter((event) => event.eventType === 'speaker_decided').map((event) => event.displayReason)).toEqual(['Beta 负责最终核对', '任务已完成，无需继续发言'])
  expect(provider.requests).toHaveLength(3)
})

test('invalid automatic schema pauses without a guessed Agent or raw provider response in Renderer', async ({ desktop, provider }) => {
  const agents = await team(desktop, provider)
  await desktop.page.getByLabel('群聊调度模型', { exact: true }).selectOption({ label: 'local-e2e-model' })
  await desktop.page.getByRole('button', { name: '保存群聊配置', exact: true }).click()
  await sendWithConsent(desktop.page, '检查非法调度响应')
  await expect.poll(() => provider.requests.length).toBe(1)
  provider.json(JSON.stringify({ nextSpeaker: agents[0].id, reason: 'PRIVATE_INVALID_DECISION', extra: true }))
  await paused(desktop.page)
  await expect(desktop.page.getByRole('region', { name: 'CEO 任务控制' })).toContainText('自动调度不可用')
  expect((await snapshot(desktop.page)).turns).toHaveLength(0)
  expect(provider.requests).toHaveLength(1)
  await expect(desktop.page.locator('body')).not.toContainText('PRIVATE_INVALID_DECISION')
})

test('missing scheduler pauses instead of picking the first member; manual assignment and restart require explicit CEO control', async ({ desktop, provider }) => {
  const agents = await team(desktop, provider)
  await sendWithConsent(desktop.page, '尚未指派任何成员')
  await paused(desktop.page)
  expect(provider.requests).toHaveLength(0)
  expect((await snapshot(desktop.page)).turns).toHaveLength(0)
  await desktop.page.getByLabel('下一位 Agent', { exact: true }).selectOption({ label: 'Beta' })
  await desktop.page.getByRole('button', { name: '指派并继续', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(1)
  provider.delta('Beta 先行处理。'); provider.complete()
  await paused(desktop.page)
  await desktop.restart()
  await paused(desktop.page)
  expect(provider.requests).toHaveLength(1)
  expect((await snapshot(desktop.page)).turns.map((turn) => turn.agentId)).toEqual([agents[1].id])
  await desktop.page.getByLabel('下一位 Agent', { exact: true }).selectOption({ label: 'Alpha' })
  await desktop.page.getByRole('button', { name: '指派并继续', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(2)
  provider.delta('Alpha 按 CEO 新指派处理。'); provider.complete()
  await paused(desktop.page)
  await desktop.page.getByRole('button', { name: '结束当前任务', exact: true }).click()
  await expect(desktop.page.getByRole('button', { name: '发送消息', exact: true })).toBeVisible()
  expect((await snapshot(desktop.page)).turns.map((turn) => turn.agentId)).toEqual([agents[1].id, agents[0].id])
})

test('pending approval blocks Beta; executing one overwrite still requires explicit continuation', async ({ desktop, provider }) => {
  await writeWorkspaceFile(desktop, 'existing.md', '原始内容')
  const agents = await team(desktop, provider, ['write_file'])
  await mentions(desktop.page, ['Alpha', 'Beta']); await submitFirst(desktop.page)
  await expect.poll(() => provider.requests.length).toBe(1)
  provider.toolCall('write_file', { path: 'existing.md', content: '审批后写入' }, 'v03-overwrite')
  const controls = desktop.page.getByRole('region', { name: 'CEO 任务控制' })
  await expect(controls).toContainText('等待 CEO 审批')
  await expect(controls.getByRole('button', { name: '继续当前任务', exact: true })).toBeDisabled()
  await desktop.page.reload()
  await desktop.page.getByRole('tab', { name: '工具与审批', exact: true }).click()
  const approvals = desktop.page.getByRole('region', { name: '安全审批', exact: true })
  await approvals.getByRole('button', { name: '批准', exact: true }).click()
  await expect(approvals).toContainText('approved')
  await expect(desktop.page.getByRole('button', { name: '继续当前任务', exact: true })).toBeDisabled()
  expect(await readFile(join(desktop.workspace, 'existing.md'), 'utf8')).toBe('原始内容')
  expect(provider.requests).toHaveLength(1)
  await approvals.getByRole('button', { name: '执行已批准操作', exact: true }).click()
  await expect.poll(async () => readFile(join(desktop.workspace, 'existing.md'), 'utf8')).toBe('审批后写入')
  await expect(desktop.page.getByRole('button', { name: '继续当前任务', exact: true })).toBeEnabled()
  expect(provider.requests).toHaveLength(1)
  let state = await snapshot(desktop.page)
  const [approval] = await desktop.page.evaluate((id) => window.agentTeam.approvals.list(id), state.runs[0].id)
  expect(await desktop.page.evaluate(async (id) => { try { await window.agentTeam.approvals.runApproved(id); return false } catch { return true } }, approval.id)).toBe(true)
  await desktop.page.getByRole('button', { name: '继续当前任务', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(2)
  expect(JSON.stringify(provider.requests[1].messages)).toContain('你是 Alpha')
  provider.delta('Alpha 已核验审批效果，不重复写入。'); provider.complete()
  await expect.poll(() => provider.requests.length).toBe(3)
  provider.delta('Beta 继续核对。'); provider.complete()
  await paused(desktop.page)
  state = await snapshot(desktop.page)
  expect(state.turns.map((turn) => [turn.agentId, turn.status])).toEqual([[agents[0].id, 'cancelled'], [agents[0].id, 'completed'], [agents[1].id, 'completed']])
  const tools = await desktop.page.evaluate((id) => window.agentTeam.tools.list(id), state.runs[0].id)
  expect(tools).toHaveLength(1); expect(tools[0].status).toBe('completed')
  expect(await readFile(join(desktop.workspace, 'existing.md'), 'utf8')).toBe('审批后写入')
})

test('CEO interruption disconnects old stream and rejects a late previous Run fragment', async ({ desktop, provider }) => {
  const agents = await team(desktop, provider)
  await mentions(desktop.page, ['Alpha']); await submitFirst(desktop.page)
  await expect.poll(() => provider.requests.length).toBe(1)
  provider.delta('旧任务临时输出')
  await expect(desktop.page.getByRole('log')).toContainText('旧任务临时输出')
  const previous = await snapshot(desktop.page)
  await mentions(desktop.page, ['Beta'], '改为核对新目标 ')
  await desktop.page.getByRole('button', { name: '中断并发送新指令', exact: true }).click()
  await expect.poll(() => provider.disconnectedRequests).toContain(0)
  await expect.poll(() => provider.requests.length).toBe(2)
  // Simulate an already queued Main-to-Preload fragment from the cancelled scope.
  await desktop.app.evaluate(({ BrowserWindow }, stale) => {
    BrowserWindow.getAllWindows()[0].webContents.send('message:stream', stale)
  }, { taskRunId: previous.runs[0].id, generation: previous.runs[0].generation, turnId: previous.turns[0].id, agentId: agents[0].id, step: 1, type: 'delta', content: 'LATE_OLD_RUN_FRAGMENT' })
  provider.delta('Beta 新任务完成。'); provider.complete()
  await paused(desktop.page)
  await expect(desktop.page.getByRole('log')).not.toContainText('LATE_OLD_RUN_FRAGMENT')
  await expect(desktop.page.getByRole('log')).not.toContainText('旧任务临时输出')
  const state = await snapshot(desktop.page)
  expect(state.runs.map((run) => run.status)).toEqual(['cancelled', 'paused'])
  expect(state.messages.map((message) => message.authorName)).toEqual(['CEO', 'CEO', 'Beta'])
})

test('CEO interruption uses the newly selected conversation model and requires its own consent', async ({ desktop, provider }) => {
  await createProject(desktop)
  const { page } = desktop
  await configureModel(page, provider.url)
  await sendWithConsent(page, '旧模型的任务')
  await expect.poll(() => provider.requests.length).toBe(1)
  expect(provider.requests[0].model).toBe('local-e2e-model')
  const old = await snapshot(page)
  await page.getByRole('button', { name: '模型设置', exact: true }).click()
  const settings = page.getByRole('dialog', { name: '模型设置', exact: true })
  await settings.getByRole('combobox', { name: '模型服务商', exact: true }).selectOption('openai')
  await settings.getByLabel('服务地址', { exact: true }).fill(provider.url)
  await settings.getByLabel('模型名称', { exact: true }).fill('replacement-e2e-model')
  await settings.getByLabel('API Key', { exact: true }).fill('e2e-second-local-only-key')
  await settings.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(settings.getByRole('status')).toHaveText('模型配置已保存')
  await settings.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByLabel('对话模型').locator('option:checked')).toHaveText('replacement-e2e-model')
  const selected = (await page.evaluate(() => window.agentTeam.models.list())).find((model) => model.modelName === 'replacement-e2e-model')!
  await page.getByLabel('消息内容', { exact: true }).fill('新模型处理的新目标')
  await page.getByRole('button', { name: '中断并发送新指令', exact: true }).click()
  const consent = page.getByRole('dialog', { name: '云端模型授权' })
  await expect(consent).toContainText('replacement-e2e-model')
  expect(provider.requests).toHaveLength(1)
  expect((await snapshot(page)).runs[0].status).toBe('running')
  await consent.getByRole('checkbox').check(); await consent.getByRole('button', { name: '同意并发送', exact: true }).click()
  await expect.poll(() => provider.disconnectedRequests).toContain(0)
  await expect.poll(() => provider.requests.length).toBe(2)
  expect(provider.requests[1]).toMatchObject({ model: 'replacement-e2e-model', stream: true })
  expect(provider.requests[1].messages.at(-1)?.content).toBe('新模型处理的新目标')
  provider.delta('新模型任务已完成。'); provider.complete()
  await expect(page.getByText('已完成', { exact: true })).toBeVisible()
  const state = await snapshot(page)
  expect(state.runs.map((run) => [run.modelConfigId, run.status])).toEqual([[old.runs[0].modelConfigId, 'cancelled'], [selected.id, 'completed']])
})

test('restart during an Agent stream pauses without replay and resumes only after an explicit click', async ({ desktop, provider }) => {
  await team(desktop, provider)
  await mentions(desktop.page, ['Alpha']); await submitFirst(desktop.page)
  await expect.poll(() => provider.requests.length).toBe(1)
  provider.delta('重启前未完成分片')
  await expect(desktop.page.getByRole('log')).toContainText('重启前未完成分片')
  await desktop.restart()
  await paused(desktop.page)
  expect(provider.requests).toHaveLength(1)
  await expect(desktop.page.getByRole('log')).not.toContainText('重启前未完成分片')
  await desktop.page.getByRole('button', { name: '继续当前任务', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(2)
  provider.delta('恢复后新一轮完整输出。'); provider.complete()
  await paused(desktop.page)
  const state = await snapshot(desktop.page)
  expect(state.turns.map((turn) => turn.status)).toEqual(['cancelled', 'completed'])
  expect(state.messages.map((message) => message.content)).not.toContain('重启前未完成分片')
  expect(state.runs[0].generation).toBeGreaterThan(state.turns[0].generation)
})
