import { test, expect, configureModel, createProject } from './fixtures'

test('Model Hub edits without exposing keys, tests/defaults a config and discovers a local Ollama model', async ({ desktop, provider }) => {
  await createProject(desktop)
  const { page } = desktop
  await configureModel(page, provider.url)
  const [original] = await page.evaluate(() => window.agentTeam.models.list())
  await page.getByRole('button', { name: '模型设置', exact: true }).click()
  const settings = page.getByRole('dialog', { name: '模型设置', exact: true })
  await settings.getByRole('combobox', { name: '已有配置', exact: true }).selectOption(original.id)
  await expect(settings.getByLabel('API Key', { exact: true })).toHaveValue('')
  await settings.getByLabel('模型名称', { exact: true }).fill('edited-cloud-model')
  await settings.getByLabel('上下文窗口', { exact: true }).fill('16000')
  await settings.getByLabel('最大输出 Token', { exact: true }).fill('2000')
  await settings.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(settings.getByRole('status')).toHaveText('模型配置已保存')
  const [edited] = await page.evaluate(() => window.agentTeam.models.list())
  expect(edited).toMatchObject({ id: original.id, modelName: 'edited-cloud-model', hasApiKey: true, contextWindow: 16000, maxOutputTokens: 2000 })
  expect(JSON.stringify(edited)).not.toContain('e2e-local-only-key')
  await settings.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(1)
  expect(provider.requests[0]).toMatchObject({ model: 'edited-cloud-model', stream: false })
  provider.json('ok')
  await expect(settings.getByRole('status')).toHaveText('模型连接正常')
  await settings.getByRole('combobox', { name: '默认调度模型', exact: true }).selectOption(original.id)
  await expect.poll(() => page.evaluate(() => window.agentTeam.models.getDefaultScheduler())).toBe(original.id)

  await settings.getByRole('combobox', { name: '已有配置', exact: true }).selectOption('')
  await settings.getByRole('combobox', { name: '模型服务商', exact: true }).selectOption('ollama')
  await settings.getByLabel('服务地址', { exact: true }).fill(provider.url)
  await settings.getByRole('button', { name: '发现本机模型', exact: true }).click()
  await expect(settings.getByRole('status')).toHaveText('已读取本机模型')
  await expect(settings.locator('#ollama-models option')).toHaveAttribute('value', 'local-ollama-test')
  await expect(settings.getByLabel('API Key', { exact: true })).toHaveCount(0)
  await settings.getByLabel('模型名称', { exact: true }).fill('local-ollama-test')
  await settings.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(settings.getByRole('status')).toHaveText('模型配置已保存')
  await settings.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByLabel('对话模型').locator('option:checked')).toHaveText('local-ollama-test')
  await page.getByLabel('消息内容', { exact: true }).fill('本机模型验收')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect.poll(() => provider.requests.length).toBe(2)
  await expect(page.getByRole('dialog', { name: '云端模型授权' })).toHaveCount(0)
  expect(provider.ollamaChecks).toContain('tags')
  expect(provider.ollamaChecks).toContain('show:local-ollama-test')
  provider.delta('本机模型完整回复。'); provider.complete()
  await expect(page.getByText('已完成', { exact: true })).toBeVisible()
  await desktop.restart()
  const models = await desktop.page.evaluate(() => window.agentTeam.models.list())
  expect(models.map((model) => model.modelName)).toEqual(['edited-cloud-model', 'local-ollama-test'])
  expect(models[1].hasApiKey).toBe(false)
  expect(models.every((model) => !('encryptedApiKey' in model) && !('apiKey' in model))).toBe(true)
  expect(await desktop.page.evaluate(() => window.agentTeam.models.getDefaultScheduler())).toBe(original.id)
  await expect(desktop.page.locator('body')).not.toContainText('e2e-local-only-key')
})
