export enum IpcChannel {
  ProjectCreate = 'project:create',
  ProjectList = 'project:list',
  ChannelCreate = 'channel:create',
  ChannelList = 'channel:list',
  MessageSend = 'message:send',
  TaskRunCancel = 'task-run:cancel',
  ModelSave = 'model:save',
  ModelList = 'model:list',
  MessageStream = 'message:stream',
  MessageList = 'message:list',
  TaskRunList = 'task-run:list',
  CloudConsentHas = 'cloud-consent:has',
  CloudConsentGrant = 'cloud-consent:grant',
}
