export enum IpcChannel {
  ProjectCreate = 'project:create',
  ProjectList = 'project:list',
  ProjectPickWorkspace = 'project:pick-workspace',
  ChannelCreate = 'channel:create',
  ChannelList = 'channel:list',
  MessageSend = 'message:send',
  TaskRunCancel = 'task-run:cancel',
  ModelSave = 'model:save',
  ModelList = 'model:list',
  MessageStream = 'message:stream',
  MessageList = 'message:list',
  TaskRunList = 'task-run:list',
  CloudConsentHas = 'cloud-consent:has',
  CloudConsentGrant = 'cloud-consent:grant',
  AgentList = 'agent:list',
  AgentGet = 'agent:get',
  AgentCreate = 'agent:create',
  AgentUpdate = 'agent:update',
  AgentRemove = 'agent:remove',
  ChannelAgentList = 'channel-agent:list',
  ChannelAgentSave = 'channel-agent:save',
  ChannelAgentRemove = 'channel-agent:remove',
}
